export const VIETNAM_PROVINCES = [
    // 6 Thành phố trực thuộc Trung ương
    "Thành phố Hà Nội",
    "Thành phố Hải Phòng",
    "Thành phố Huế",
    "Thành phố Đà Nẵng",
    "Thành phố Hồ Chí Minh",
    "Thành phố Cần Thơ",
    // 28 Tỉnh
    "An Giang",
    "Bắc Ninh",
    "Cà Mau",
    "Cao Bằng",
    "Đắk Lắk",
    "Điện Biên",
    "Đồng Nai",
    "Đồng Tháp",
    "Gia Lai",
    "Hà Tĩnh",
    "Hưng Yên",
    "Khánh Hòa",
    "Lai Châu",
    "Lạng Sơn",
    "Lào Cai",
    "Nghệ An",
    "Ninh Bình",
    "Phú Thọ",
    "Quảng Ngãi",
    "Quảng Ninh",
    "Quảng Trị",
    "Sơn La",
    "Tây Ninh",
    "Thái Nguyên",
    "Thanh Hoá",
    "Tuyên Quang",
    "Vĩnh Long",
    "Lâm Đồng"
];
