create table if not exists public.site_announcements (
    id bigint generated by default as identity primary key,
    message text not null,
    created_by text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create or replace function public.set_site_announcements_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_site_announcements_updated_at on public.site_announcements;

create trigger trg_site_announcements_updated_at
before update on public.site_announcements
for each row
execute function public.set_site_announcements_updated_at();
