create table if not exists public.wiki_post_edit_history (
    id bigint generated by default as identity primary key,
    post_slug text not null,
    editor_username text not null,
    editor_display_name text,
    edit_reason text not null,
    edited_at timestamptz not null default timezone('utc', now())
);

create index if not exists wiki_post_edit_history_post_slug_edited_at_idx
on public.wiki_post_edit_history (post_slug, edited_at desc);
