alter table public.wiki_posts
add column if not exists author_role text not null default 'admin',
add column if not exists approved_submission_id bigint;

update public.wiki_posts
set author_role = coalesce(author_role, 'admin')
where author_role is null;

create table if not exists public.wiki_submissions (
    id bigint generated by default as identity primary key,
    title text not null,
    slug text not null,
    excerpt text not null,
    content text not null,
    author text not null,
    author_role text not null default 'member',
    category text not null,
    image_url text,
    read_time text not null,
    status text not null default 'pending',
    review_notes text,
    reviewed_by text,
    reviewed_at timestamptz,
    published_post_slug text,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    constraint wiki_submissions_author_role_check check (author_role in ('admin', 'member')),
    constraint wiki_submissions_status_check check (status in ('pending', 'approved', 'rejected'))
);

create index if not exists wiki_submissions_status_idx on public.wiki_submissions (status, created_at desc);
create index if not exists wiki_submissions_author_idx on public.wiki_submissions (author, created_at desc);
create unique index if not exists wiki_submissions_active_slug_idx
on public.wiki_submissions (slug)
where status in ('pending', 'approved');

create or replace function public.set_wiki_submission_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists wiki_submissions_set_updated_at on public.wiki_submissions;

create trigger wiki_submissions_set_updated_at
before update on public.wiki_submissions
for each row
execute function public.set_wiki_submission_updated_at();
